### ISSUE TITLE
The report subcommand skips repos with < 5 forks

### ISSUE THREAD

**Issue by kylog** [puppetlabs/maintainers#22]
The report subcommand currently skips repos with < 5 forks. This is done in an attempt to speed up reporting, but it means the report is necessarily incomplete.

**Comment by garethr** [comment]
@kylog makes sense. I think the issue I foresee is that will exclude things that are small and new - so teams with a higher repo count per team member, especially if that code is private, will drop off the reporting.

**Comment by kylog** [comment]
Yep, that's definitely the downside and we need a fix so that the reporting is accurate. 

Btw though, do note that the code being private is immaterial to this issue per se - if you run the report with a `GITHUB_TOKEN` set to something with access to puppetlabs private repos, it will report on them.

**Comment by garethr** [comment]
@kylog the private repo point was more about the available population who can fork to pass the 5 forks barrier. A public repo is more likely to garner forks as anyone can fork it. For example see https://github.com/puppetlabs/puppet-in-docker/network/members. This repo has 13 forks, but only because it's public. All the forks are from people outside Puppet, so as a private repo it would fall below the threshold and not be reported.
