### ISSUE TITLE
Potential confusion with version

### ISSUE THREAD

**Issue by garethr** [puppetlabs/maintainers#8]
The MAINTAINERS file ends up with a `version` field, which is currently 1.

`"version": 1`

This is the version of the schema, rather than the version of the file itself. I'm wondering whether that should be explicit, ie. `schema_version`.

**Comment by kylog** [comment]
Yes, that concern on an early PR is part of what inspired the `file_format` field. 

Fwiw I was following the example of https://github.com/puppetlabs/trapperkeeper-authorization/blob/master/doc/authorization-config.md which uses `version` in the same way. I have no history for whether the same concern has occurred there. (I also wonder if your idea in #9 of pointing directly at the schema rather than the repo root would mitigate this concern a bit.)
